# Generated by Django 2.2.2 on 2019-06-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2',
            name='nth',
            field=models.IntegerField(default=0),
        ),
    ]
